version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app2
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver2
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:   # ✅ NOW CORRECTLY PLACED
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin2
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: